import type { PatchModule } from './types'

export const PATCHES: PatchModule[] = [
  {
    id: 'multithread',
    code: 'THREAD+',
    name: '멀티스레드',
    symbol: 'Ⅱ',
    mergeTitle: '병렬 처리',
    mergeDescription: '매 라운드 추가 공 1개를 생성합니다.',
    debtTitle: '병렬 공격',
    debtDescription: '보스가 동시에 더 많은 공격을 발사합니다.',
  },
  {
    id: 'firewall',
    code: 'WALL_01',
    name: '방화벽',
    symbol: '◇',
    mergeTitle: '하단 방어',
    mergeDescription: '라운드마다 공 낙하를 한 번 무효화합니다.',
    debtTitle: '재생 보호막',
    debtDescription: '보스에게 충전식 보호막이 생깁니다.',
  },
  {
    id: 'overclock',
    code: 'CLK_MAX',
    name: '오버클럭',
    symbol: '▲',
    mergeTitle: '출력 증폭',
    mergeDescription: '공 속도와 보스 피해량이 증가합니다.',
    debtTitle: '긴급 가속',
    debtDescription: '보스의 체력이 낮아지면 공격이 빨라집니다.',
  },
  {
    id: 'cache',
    code: 'CACHE++',
    name: '확장 캐시',
    symbol: '▰',
    mergeTitle: '넓은 패들',
    mergeDescription: '패들 폭이 35% 증가합니다.',
    debtTitle: '데이터 정체',
    debtDescription: '보스가 공을 느리게 만드는 정체 파동을 보냅니다.',
  },
  {
    id: 'recursion',
    code: 'RECUR()',
    name: '재귀 호출',
    symbol: '∞',
    mergeTitle: '에코 볼',
    mergeDescription: '연속 타격 시 임시 공이 복제됩니다.',
    debtTitle: '버그 복제',
    debtDescription: '파괴한 블록 일부가 다시 생성됩니다.',
  },
  {
    id: 'targeting',
    code: 'AIM_AI',
    name: '타기팅 AI',
    symbol: '◎',
    mergeTitle: '정밀 보정',
    mergeDescription: '패들 반사 시 공이 가까운 목표를 향합니다.',
    debtTitle: '추적 탄환',
    debtDescription: '보스의 탄환이 패들을 조준합니다.',
  },
  {
    id: 'rollback',
    code: 'ROLLBACK',
    name: '롤백',
    symbol: '↶',
    mergeTitle: '복구 지점',
    mergeDescription: '빌드 안정도 1칸을 즉시 복구합니다.',
    debtTitle: '보스 복원',
    debtDescription: '쓰러진 보스가 한 번 체력을 복원합니다.',
  },
  {
    id: 'hotfix',
    code: 'HOT_FIX',
    name: '핫픽스',
    symbol: '✦',
    mergeTitle: '연쇄 수정',
    mergeDescription: '블록 7개마다 추가 블록을 자동 제거합니다.',
    debtTitle: '자가 수리',
    debtDescription: '보스가 전투 중 자신의 체력을 수리합니다.',
  },
]

export const patchById = Object.fromEntries(PATCHES.map((patch) => [patch.id, patch])) as Record<
  PatchModule['id'],
  PatchModule
>
